In [1]:
# Standard imports
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set_context("talk")

# Numpy Review

This is a brief overview of numpy for [DS100](http://ds100.org).  The Jupyter Notebook can be obtained here: [Numpy_Review.ipynb](http://ds100.org/fa17/assets/notebooks/numpy/Numpy_Review.ipynb).

# Importing Numpy

It is customary to import Numpy as `np`:

In [2]:
import numpy as np

As you learned in homework one the `np.array` is the key data structure in numpy for dense arrays of data.

# Creating Arrays

You can build arrays from python lists. 
**Data 8 Compatibility:** In data8 you used a `datascience` package function called `make_array` which wraps the more standard `np.array` function we will use in this class.

In [3]:
np.array([[1.,2.], [3.,4.]])

array([[ 1.,  2.],
       [ 3.,  4.]])

In [4]:
np.array([x for x in range(5)])

array([0, 1, 2, 3, 4])

Array's don't have to contain numbers:

In [5]:
np.array([["A", "matrix"], ["of", "words."]])

array([['A', 'matrix'],
       ['of', 'words.']], 
      dtype='<U6')

## Making Arrays of Zeros

In [6]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

## Making Arrays of Ones

In [7]:
np.ones([3,2])

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [8]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Making Arrays from ranges:

The `np.arange(start, stop, step)` function is like the python `range` function.

In [9]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

You can make a range of other types as well:

In [10]:
np.arange(np.datetime64('2016-12-31'), np.datetime64('2017-02-01'))

array(['2016-12-31', '2017-01-01', '2017-01-02', '2017-01-03',
       '2017-01-04', '2017-01-05', '2017-01-06', '2017-01-07',
       '2017-01-08', '2017-01-09', '2017-01-10', '2017-01-11',
       '2017-01-12', '2017-01-13', '2017-01-14', '2017-01-15',
       '2017-01-16', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-21', '2017-01-22', '2017-01-23',
       '2017-01-24', '2017-01-25', '2017-01-26', '2017-01-27',
       '2017-01-28', '2017-01-29', '2017-01-30', '2017-01-31'], dtype='datetime64[D]')

## Interpolating numbers 

The `linspace(start,end,num)` function generates `num` numbers evenly spaced between the `start` and `end`.

In [11]:
np.linspace(0, 5, 10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

Learn more about working with [datetime objects](https://docs.scipy.org/doc/numpy/reference/arrays.datetime.html#).

## A random array 

You can also generate arrays of random numbers (we will cover this in greater detail later).

- `randn` generates random numbers from a Normal(mean=0, var=1) distribution.
- `rand` generates random numbers from a Uniform(low=0, high=1) distribution.
- `permutation` generates a random permutation of a sequence of numbers.

In [12]:
np.random.randn(3,2)

array([[ 0.3601399 ,  1.31206686],
       [-0.95112397,  0.62475726],
       [-1.24179768,  1.63392069]])

In [13]:
np.random.rand(3,2)

array([[ 0.2703233 ,  0.26231929],
       [ 0.44311229,  0.06318871],
       [ 0.31311525,  0.40825175]])

In [14]:
np.random.permutation(range(0,10))

array([4, 2, 5, 9, 1, 0, 8, 3, 6, 7])


# Properties of Arrays

## Shape

Arrays have a shape which corresponds to the number of rows, columns, fibers, ...

In [15]:
A = np.array([[1., 2., 3.], [4., 5., 6.]])
print(A)
A.shape

[[ 1.  2.  3.]
 [ 4.  5.  6.]]


(2, 3)

## Type

Arrays have a type which corresponds to the type of data they contain

In [16]:
A.dtype

dtype('float64')

In [17]:
np.arange(1,5).dtype

dtype('int64')

In [18]:
(np.array([True, False])).dtype

dtype('bool')

In [19]:
np.array(["Hello", "Worlddddd!"]).dtype

dtype('<U10')

What does `<U6` mean?

- `<` Little Endian
- `U` Unicode
- `6` length of longest string

#### and we can change the type of an array:

In [20]:
np.array([1,2,3]).astype(float)

array([ 1.,  2.,  3.])

In [21]:
np.array(["1","2","3"]).astype(int)

array([1, 2, 3])

Learn more about numpy [array types](https://docs.scipy.org/doc/numpy/user/basics.types.html)

## Polymorphism 

Can an array have more than one type?

In [22]:
np.array([1,2,3, "cat", True])

array(['1', '2', '3', 'cat', 'True'], 
      dtype='<U21')

Does the following command work:
```python
x = np.array([1,2,3,4])
x[3] = "cat"
```

In [23]:
x = np.array([1,2,3,4])
# x[3] = "cat" # <-- uncomment this line to find out


# Jagged Arrays

Is the following valid?

```python
A = np.array([[1, 2, 3], [4, 5], [6]])
```

In [24]:
A = np.array([[1, 2, 3], [4, 5], [6]])
A

array([[1, 2, 3], [4, 5], [6]], dtype=object)

What happened? 

In [25]:
A.shape

(3,)

In [26]:
print(A.dtype)

object


In [27]:
print(A[0])
print(A[1])
print(A[2])

[1, 2, 3]
[4, 5]
[6]


### Issues with Jagged Arrays

 <img src="http://csharpcorner.mindcrackerinc.netdna-cdn.com/UploadFile/955025/C-Sharp-interview-question-part2/Images/jagged%20array.png">

### Jagged arrays can be problematic:

1. Difficult to index (extract columns).
```python
A[0,1] 
 > Error
A[0][1] 
 > 2
```
1. Not as efficiently represented in contiguous memory.

# Reshaping

Often you will need to reshape matrices.  Suppose you have the following array:

In [28]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

**What will the following produce:**

```python
np.arange(1,13).reshape(4,3)
```

**Option A:**

```python
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])
```

**Option B:**

```python
array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])
```

**Solution**

In [29]:
A = np.arange(1,13).reshape(4,3)
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Flatting Matrix

Flattening a matrix (higher dimensional array) produces a one dimensional array.

In [30]:
A.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Advanced: Array representation

Numpy stores data contiguously in memory

In [31]:
print(A.dtype)
A.data.tobytes()

int64


b'\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\t\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x0b\x00\x00\x00\x00\x00\x00\x00\x0c\x00\x00\x00\x00\x00\x00\x00'

Numpy stores matrices in _row-major_ order (by rows)

In [32]:
print(np.arange(1,13).reshape(4,3, order='C'))
print()
print(np.arange(1,13).reshape(4,3, order='F'))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


What does the `'F'` mean?

**F**ortran ordering.  In BLAS libraries are specified for Fortran and C programming languages which differ both in the column (Fortran) or row (C) indexing.

# Slicing

From homework 1 you should already be pretty good at Slicing so let's test your slicing knowledge.

<img src="guessing_game.png" width="600px">

* **Program 1:**
```python
x[:, 0]
```
<details>
<summary>**Answer**</summary>
<p>B</p>
</details>

<br/>

* **Program 2:**
```python
x[0, :]
```
<details>
<summary>**Answer**</summary>
<p>A</p>
</details>

<br/>

* **Program 3:**
```python
x[:2, 1:]
```
<details>
<summary>**Answer**</summary>
<p>H</p>
</details>

<br/>

* **Program 4:**
```python
x[0::2, :]
```
<details>
<summary>**Answer**</summary>
<p>D</p>
</details>



<img src="guessing_game.png" width="600px">


Understanding the slice syntax

```python
begin:end:stride
```


## Modifying a Slice

Suppose I wanted to make all entries in my matrix 0 in the top right corner as in (H) above.

In [33]:
H = np.arange(1,13).reshape(4,3)
print("Before:\n", H)

Before:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [34]:
H[:2, 1:] = 0
print("After:\n", H)

After:
 [[ 1  0  0]
 [ 4  0  0]
 [ 7  8  9]
 [10 11 12]]


# Boolean Indexing

We can apply boolean operations to arrays.  This is essential when trying to select and modify individual elements.


**Question:** *Given the following definition of A:*

```python
[[   1.    2.    3.]
 [   4.    5. -999.]
 [   7.    8.    9.]
 [  10. -999. -999.]]
```

*what will the following output:*
```python
A > 3
```


- **Option A:**

```python
False
```

- **Option B:**

```python
array([[False, False, False],
       [ True,  True, False],
       [ True,  True,  True],
       [ True, False, False]], dtype=bool)
```

In [35]:
A = np.array([[  1.,   2.,   3.],
       [  4.,   5.,   -999.0],
       [  7.,   8.,   9.],
       [ 10.,  -999.0,  -999.0]])

A > 3.

array([[False, False, False],
       [ True,  True, False],
       [ True,  True,  True],
       [ True, False, False]], dtype=bool)

**Question:** *What will the following output*
```python
A = np.array([[   1.,    2.,    3.],
       [   4.,    5., -999.],
       [   7.,    8.,    9.],
       [  10., -999., -999.]])

A[A > 3]
```


- **Option A:**

```python
array([ 4,  7, 10,  5,  8, 11,  6,  9, 12])
```

- **Option B:**

```python
array([  4.,   5.,   7.,   8.,   9.,  10.])
```


- **Option C:**

```python
array([[  nan,   nan,  nan],
       [  4.,    5.,   nan],
       [  7.,    8.,   9.],
       [ 10.,    nan,  nan]])
```

In [36]:
A = np.array([[  1.,   2.,   3.],
       [  4.,   5.,   -999.0],
       [  7.,   8.,   9.],
       [ 10.,  -999.0,  -999.0]])

A[A > 3] 

array([  4.,   5.,   7.,   8.,   9.,  10.])

**Question:** *Replace the -999.0 entries with `np.nan`.*

```python
array([[   1.,    2.,    3.],
       [   4.,    5., -999.],
       [   7.,    8.,    9.],
       [  10., -999., -999.]])
```

**Solution**

In [37]:
A = np.array([[  1.,   2.,   3.],
       [  4.,   5.,   -999.0],
       [  7.,   8.,   9.],
       [ 10.,  -999.0,  -999.0]])

* Construct a boolean array that indicates where the value is 999.0:

In [38]:
ind = (A == -999.0)
print(ind)

[[False False False]
 [False False  True]
 [False False False]
 [False  True  True]]


* Assign `np.nan` to all the `True` entires:

In [39]:
A[ind] = np.nan
A

array([[  1.,   2.,   3.],
       [  4.,   5.,  nan],
       [  7.,   8.,   9.],
       [ 10.,  nan,  nan]])

**Question:** *What might -999.0 represent?  Why might I want to replace the -999.0 with a `np.nan`?  *

**Solution:** It could be safer in calculations.  For example when computing the mean of the transformed A we get:

In [40]:
print(A)
np.mean(A)

[[  1.   2.   3.]
 [  4.   5.  nan]
 [  7.   8.   9.]
 [ 10.  nan  nan]]


nan

Perhaps instead we want:

In [41]:
np.nanmean(A)

5.4444444444444446

In [42]:
help(np.nanmean)

Help on function nanmean in module numpy.lib.nanfunctions:

nanmean(a, axis=None, dtype=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)
    Compute the arithmetic mean along the specified axis, ignoring NaNs.
    
    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.
    
    For all-NaN slices, NaN is returned and a `RuntimeWarning` is raised.
    
    .. versionadded:: 1.8.0
    
    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : int, optional
        Axis along which the means are computed. The default is to compute
        the mean of the flattened array.
    dtype : data-type, optional
        Type to use in computing the mean.  For integer inputs, the default
        is `float64`; for

# More Complex Bit Logic

Often we will want to work with multiple different arrays at once and select subsets of entries from each array.  Consider the following example:

In [43]:
names = np.array(["Joey", "Henry", "Joseph", 
                  "Jim", "Sam", "Deb", "Mike", 
                  "Bin", "Joe", "Andrew", "Bob"])

favorite_number = np.arange(len(names)) 

Suppose a subset of these people are staff members:

In [44]:
staff = ["Joey",  "Deb", "Sam"]

### Question:
*How could we compute the sum of the staff members favorite numbers?*

One solution is to use for loops:

In [45]:
total = 0 
for i in range(len(names)):
    if names[i] in staff:
        total += favorite_number[i]

print("total:", total)

total: 9


Another solution would be to use the [np.in1d](https://docs.scipy.org/doc/numpy/reference/generated/numpy.in1d.html) function to determine which people are staff.

In [46]:
is_staff = np.in1d(names, staff)
is_staff

array([ True, False, False, False,  True,  True, False, False, False,
       False, False], dtype=bool)

Boolean indexing

In [47]:
favorite_number[is_staff].sum()

9

### Question:
*What does the following expression compute:*

```python
starts_with_j = np.char.startswith(names, "J")
starts_with_j[is_staff].mean()
```

The fraction of the staff have names that begin with `J`?

In [48]:
starts_with_j = np.char.startswith(names, "J")
starts_with_j[is_staff].mean()

0.33333333333333331

### Question:
*What does it mean to take the mean of an array of booleans?*

The values `True` and `False` correspond to the integers `1` and `0` and are treated as such in mathematical expressions (e.g., `mean()`, `sum()`, as well as linear algebraic operations).

### Question
*What does the following expression compute:*

```python
favorite_number[starts_with_j & is_staff].sum()
```

The sum of the favorite numbers of staff starting with `J`

In [49]:
favorite_number[starts_with_j & is_staff].sum()

0

## Other Useful Operations

* [`choose()`](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.choose.html)
* [`where()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html)



# A Note on using Array operations

In [50]:
data = np.random.rand(1000000)

Consider the following two programs.  


### Program A
```python
s = 0
c = 0
for x in data:
    if x > 0.5:
        s += x
        c += 1
result = s/c
```

### Program B
```python
result = data[data > 0.5].mean()
```

1. What do they do?
1. Which one is faster?
1. Which one is clearer?

---

<br/><br/><br/><br/><br/>

### Solution

In [51]:
%%timeit
s = 0
for x in data:
    if x > 0.5:
        s += x
result = s/len(data)

10 loops, best of 3: 107 ms per loop


In [52]:
%%timeit
result = data[data > 0.5].mean()

100 loops, best of 3: 6.91 ms per loop


## Important Points

Using the array abstractions instead of looping can often be:

1. Clearer
2. Faster

These are fundamental goals of abstraction. 

---

<br/>
<br/>
<br/>
<br/>
<br/>
<br/>


# Mathematical operations:

Numpy arrays support standard mathematical operations

In [53]:
A = np.arange(1., 13.).reshape(4,3)
print(A)

[[  1.   2.   3.]
 [  4.   5.   6.]
 [  7.   8.   9.]
 [ 10.  11.  12.]]


In [54]:
A * 0.5 + 3

array([[ 3.5,  4. ,  4.5],
       [ 5. ,  5.5,  6. ],
       [ 6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ]])

notice that operations are element wise.

In [55]:
A.T

array([[  1.,   4.,   7.,  10.],
       [  2.,   5.,   8.,  11.],
       [  3.,   6.,   9.,  12.]])

In [56]:
A.sum()

78.0

In [57]:
A.mean()

6.5

<br/>
<br/>
<br/>




## Be Careful with Floating Point Numbers

What is the value of the following:
$$
A - \exp \left( \log \left( A \right) \right)
$$

<br/>
<br/>
<br/>

**Solution:**


In [58]:
A = np.arange(1., 13.).reshape(4,3)
print(A)

(A - np.exp(np.log(A)))

[[  1.   2.   3.]
 [  4.   5.   6.]
 [  7.   8.   9.]
 [ 10.  11.  12.]]


array([[  0.00000000e+00,   0.00000000e+00,  -4.44089210e-16],
       [  0.00000000e+00,   8.88178420e-16,   0.00000000e+00],
       [  8.88178420e-16,   1.77635684e-15,  -1.77635684e-15],
       [ -1.77635684e-15,  -1.77635684e-15,   0.00000000e+00]])

**What happened?!**

Floating point precision is not perfect and we are applying transcendental functions.

<br/><br/><br/><br/>
### A simpler examples

What is the value of the following expression:

```python
0.1 + 0.2 == 0.3
```

In [59]:
0.1 + 0.2 == 0.3

False

In [60]:
print(0.1 + 0.2)

0.30000000000000004


For these situations consider using `np.isclose`:

In [61]:
help(np.isclose)

Help on function isclose in module numpy.core.numeric:

isclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
    Returns a boolean array where two arrays are element-wise equal within a
    tolerance.
    
    The tolerance values are positive, typically very small numbers.  The
    relative difference (`rtol` * abs(`b`)) and the absolute difference
    `atol` are added together to compare against the absolute difference
    between `a` and `b`.
    
    Parameters
    ----------
    a, b : array_like
        Input arrays to compare.
    rtol : float
        The relative tolerance parameter (see Notes).
    atol : float
        The absolute tolerance parameter (see Notes).
    equal_nan : bool
        Whether to compare NaN's as equal.  If True, NaN's in `a` will be
        considered equal to NaN's in `b` in the output array.
    
    Returns
    -------
    y : array_like
        Returns a boolean array of where `a` and `b` are equal within the
        given tolerance. If both `a` 

<br/>
<br/>
<br/>
<br/>


## Aggregating along an axis 

<img src="axis_plot.png" width="300px">

### Grouping by row:

In [62]:
A.sum(axis=0)

array([ 22.,  26.,  30.])

This is the same as:
```python
(nrow, ncols) = A.shape

s = np.zeros(ncols)

for i in range(nrows):
    s += A[i,:]

print(s)
```

### Grouping by col:

In [63]:
A.sum(axis=1)

array([  6.,  15.,  24.,  33.])

This is the same as:
```python
(nrows, ncols) = A.shape

s = np.zeros(nrows)

for i in range(ncols):
    s += A[:,i]

print(s)
```

## Other Functions to Checkout

* [`mean`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html) computes the mean 
* [`std`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.std.html) standard deviation
* [`var`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.var.html) variance

and [many more](https://docs.scipy.org/doc/numpy/reference/ufuncs.html#math-operations)

---

<br/>
<br/>
<br/>
<br/>
<br/>
<br/>



# Linear Algebra

Suppose we wanted to use linear algebra to compute the sum along axis 1

---

$$ \texttt{A.sum( axis = 1) } = \sum_j A_{i,j} = \begin{bmatrix} 1 & 2 & 3 \\
 4 & 5 & 6\end{bmatrix} \cdot \begin{bmatrix} 1 \\ 1 \\ 1\end{bmatrix} $$

### Will the following work?

```python
b = np.ones(3)
A * b
```

---

<br/><br/><br/><br/><br/>

#### Solution

In [64]:
A = np.array([[1, 2, 3], [4, 5, 6]])
b = np.ones(3)
A * b

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])



<br/>
<br/>
<br/>
<br/>
---

**Explanation:**

We ended up computing an element-wise product.  The vector of ones was replicated once for each row and then used to scale the entire row.

<img src="broadcast_equation.png" width="300px"/>

---

### The correct expression for matrix multiplication

In [65]:
A.dot(b)

array([  6.,  15.])

In the later python versions (>3.5) you can use the infix operator `@` which is probably easier to read

In [66]:
A @ b

array([  6.,  15.])

---



<br/><br/><br/><br/><br/><br/>


# Solving Linear Systems

Suppose you are asked to solve the following system of linear equations:

$$
5x - 3y = 2 \\
-9x + 2y = -7
$$

this means that we want to solve the following linear systems:

$$
\begin{bmatrix}
5 & -3 \\ -9 & 2
\end{bmatrix} 
\begin{bmatrix}
x \\ y
\end{bmatrix}
=
\begin{bmatrix}
2 \\ -7
\end{bmatrix}
$$

Solving for $x$ and $y$ we get:

$$
\begin{bmatrix}
x \\ y
\end{bmatrix}
=
\begin{bmatrix}
5 & -3 \\ -9 & 2
\end{bmatrix}^{-1}
\begin{bmatrix}
2 \\ -7
\end{bmatrix}
$$



This can be solved numerically using NumPy:

In [67]:
A = np.array([[5, -3], [-9, 2]])
b = np.array([2,-7])

In [68]:
from numpy.linalg import inv
inv(A) @ b

array([ 1.,  1.])

Preferred way to solve (more numerically stable)

In [69]:
from numpy.linalg import solve
solve(A, b)

array([ 1.,  1.])

Two points:

1. Issue with performance
1. Issue with numerical stability 

When the matrix is not full rank it may be necessary to use [lstsq](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.lstsq.html#numpy.linalg.lstsq).